# version: "3.8"
services:
  mc:
    build: .
    ports:
      - "25565:25565"
    volumes:
      - ./world:/data/world     # persist local world
      - ./world/ops.json:/data/ops.json  # ensure ops file is in correct location
      # - ./plugins:/data/plugins  # Mount your plugins folder into the server
