services:
  minecraft-server:
    build: .
    ports:
      - "25565:25565"
    volumes:
      - ./world:/data/world
      - ./world/ops.json:/data/ops.json
      - ./plugins:/data/plugins
    restart: unless-stopped
    environment:
      - MEMORY=6G
    logging:
      driver: "gcplogs"
      options:
        gcp-project: "omnia-dev-470001"
        gcp-log-cmd: "true"
    networks:
      - omnia-network

networks:
  omnia-network:
    driver: bridge

