name: omnia
services:
  mc:
    build: .
    ports:
      - "25565:25565"
    volumes:
      - ./world:/data/world     # persist local world
      - ./world/ops.json:/data/ops.json  # ensure ops file is in correct location
      - ./plugins:/data/plugins  # Mount your plugins folder into the server
    environment:
      - MEMORY=6G
      # - ENV=${ENV:-dev}
    networks:
      omnia-network:
        # ipv4_address: 172.19.0.10
    deploy:
      resources:
        limits:
          memory: 8G
          cpus: '1.0'
        reservations:
          memory: 2G
          cpus: '0.5'

networks:
  omnia-network:
    driver: bridge
#     ipam:
#       config:
#         - subnet: 172.20.0.0/16
#           gateway: 172.20.0.1